-- AlterTable
ALTER TABLE "Bot" ADD COLUMN     "atrMultiplier" DOUBLE PRECISION,
ADD COLUMN     "tpSlRatio" DOUBLE PRECISION,
ADD COLUMN     "useDynamicSLTP" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "tp" DROP NOT NULL,
ALTER COLUMN "sl" DROP NOT NULL;
